//
//  TONConnectSession.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import BigInt


public struct TONConnectSession: Codable {

    public var sessionId: String
    /** Wallet ID format: \"network:address\" Examples: - \"-239:EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\" (mainnet) - \"-3:EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2\" (testnet) */
    public var walletId: String
    public var walletAddress: TONUserFriendlyAddress
    public var createdAt: String
    public var lastActivityAt: String
    public var privateKey: String
    public var publicKey: String
    public var domain: String
    public var dAppInfo: TONDAppInfo
    public var isJsBridge: Bool?

    public init(sessionId: String, walletId: String, walletAddress: TONUserFriendlyAddress, createdAt: String, lastActivityAt: String, privateKey: String, publicKey: String, domain: String, dAppInfo: TONDAppInfo, isJsBridge: Bool? = nil) {
        self.sessionId = sessionId
        self.walletId = walletId
        self.walletAddress = walletAddress
        self.createdAt = createdAt
        self.lastActivityAt = lastActivityAt
        self.privateKey = privateKey
        self.publicKey = publicKey
        self.domain = domain
        self.dAppInfo = dAppInfo
        self.isJsBridge = isJsBridge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionId
        case walletId
        case walletAddress
        case createdAt
        case lastActivityAt
        case privateKey
        case publicKey
        case domain
        case dAppInfo
        case isJsBridge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionId, forKey: .sessionId)
        try container.encode(walletId, forKey: .walletId)
        try container.encode(walletAddress, forKey: .walletAddress)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(lastActivityAt, forKey: .lastActivityAt)
        try container.encode(privateKey, forKey: .privateKey)
        try container.encode(publicKey, forKey: .publicKey)
        try container.encode(domain, forKey: .domain)
        try container.encode(dAppInfo, forKey: .dAppInfo)
        try container.encodeIfPresent(isJsBridge, forKey: .isJsBridge)
    }
}



