//
//  TONDeDustSwapRequest.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import BigInt

/** Swap request to DeDust Router API */

public struct TONDeDustSwapRequest: Codable {

    public var senderAddress: String
    public var swapData: TONDeDustSwapRequestSwapData
    public var referralAddress: String?
    public var referralFee: Double?
    public var jettonWalletStateInit: String?
    public var customPayload: String?

    public init(senderAddress: String, swapData: TONDeDustSwapRequestSwapData, referralAddress: String? = nil, referralFee: Double? = nil, jettonWalletStateInit: String? = nil, customPayload: String? = nil) {
        self.senderAddress = senderAddress
        self.swapData = swapData
        self.referralAddress = referralAddress
        self.referralFee = referralFee
        self.jettonWalletStateInit = jettonWalletStateInit
        self.customPayload = customPayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case senderAddress = "sender_address"
        case swapData = "swap_data"
        case referralAddress = "referral_address"
        case referralFee = "referral_fee"
        case jettonWalletStateInit = "jetton_wallet_state_init"
        case customPayload = "custom_payload"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(senderAddress, forKey: .senderAddress)
        try container.encode(swapData, forKey: .swapData)
        try container.encodeIfPresent(referralAddress, forKey: .referralAddress)
        try container.encodeIfPresent(referralFee, forKey: .referralFee)
        try container.encodeIfPresent(jettonWalletStateInit, forKey: .jettonWalletStateInit)
        try container.encodeIfPresent(customPayload, forKey: .customPayload)
    }
}




extension TONDeDustSwapRequest: JSValueCodable {}

