//
//  TONJetton.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import BigInt

/** Jetton fungible token on the TON blockchain (TEP-74 standard). */

public struct TONJetton: Codable {

    public var address: TONUserFriendlyAddress
    public var walletAddress: TONUserFriendlyAddress
    /** Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON = 10^9 nanotons). */
    public var balance: String
    public var info: TONTokenInfo
    /** The number of decimal places used by the token */
    public var decimalsNumber: Int?
    /** Additional arbitrary data related to the jetton */
    public var extra: [String: AnyCodable]?

    public init(address: TONUserFriendlyAddress, walletAddress: TONUserFriendlyAddress, balance: String, info: TONTokenInfo, decimalsNumber: Int? = nil, extra: [String: AnyCodable]? = nil) {
        self.address = address
        self.walletAddress = walletAddress
        self.balance = balance
        self.info = info
        self.decimalsNumber = decimalsNumber
        self.extra = extra
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case walletAddress
        case balance
        case info
        case decimalsNumber
        case extra
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(walletAddress, forKey: .walletAddress)
        try container.encode(balance, forKey: .balance)
        try container.encode(info, forKey: .info)
        try container.encodeIfPresent(decimalsNumber, forKey: .decimalsNumber)
        try container.encodeIfPresent(extra, forKey: .extra)
    }
}



