//
//  TONSwapQuoteParams.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import BigInt

public struct TONSwapQuoteParams<TProviderOptions: Codable>: Codable {
    public var amount: TONTokenAmount
    public var fromToken: TONSwapToken
    public var toToken: TONSwapToken
    public var network: TONNetwork
    /** Slippage tolerance in basis points (1 bp = 0.01%) */
    public var slippageBps: Double?
    /** Maximum number of outgoing messages */
    public var maxOutgoingMessages: Double?
    /** Provider-specific options */
    public var providerOptions: TProviderOptions?
    /** If true, amount is the amount to receive (buy). If false, amount is the amount to spend (sell). */
    public var isReverseSwap: Bool?

    public init(amount: TONTokenAmount, fromToken: TONSwapToken, toToken: TONSwapToken, network: TONNetwork, slippageBps: Double? = nil, maxOutgoingMessages: Double? = nil, providerOptions: TProviderOptions? = nil, isReverseSwap: Bool? = nil) {
        self.amount = amount
        self.fromToken = fromToken
        self.toToken = toToken
        self.network = network
        self.slippageBps = slippageBps
        self.maxOutgoingMessages = maxOutgoingMessages
        self.providerOptions = providerOptions
        self.isReverseSwap = isReverseSwap
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case fromToken
        case toToken
        case network
        case slippageBps
        case maxOutgoingMessages
        case providerOptions
        case isReverseSwap
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(fromToken, forKey: .fromToken)
        try container.encode(toToken, forKey: .toToken)
        try container.encode(network, forKey: .network)
        try container.encodeIfPresent(slippageBps, forKey: .slippageBps)
        try container.encodeIfPresent(maxOutgoingMessages, forKey: .maxOutgoingMessages)
        try container.encodeIfPresent(providerOptions, forKey: .providerOptions)
        try container.encodeIfPresent(isReverseSwap, forKey: .isReverseSwap)
    }
}


