//
//  TONTransactionTraceActionCallContractDetails.swift
//  TONWalletKit
//
//  Generated by openapi-generator
//
//  Copyright (c) 2025 TON Connect
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation
import BigInt


public struct TONTransactionTraceActionCallContractDetails: Codable {

    /** Opcode or method identifier of the contract call. */
    public var opcode: String
    public var source: TONUserFriendlyAddress?
    public var destination: TONUserFriendlyAddress?
    /** Token amount represented as a string to preserve precision. For TON, this is typically in nanotons (1 TON = 10^9 nanotons). */
    public var value: String?
    /** Map of extra currency IDs to their amounts. Extra currencies are additional tokens that can be attached to TON messages. */
    public var valueExtraCurrencies: [String: String]?

    public init(opcode: String, source: TONUserFriendlyAddress? = nil, destination: TONUserFriendlyAddress? = nil, value: String? = nil, valueExtraCurrencies: [String: String]? = nil) {
        self.opcode = opcode
        self.source = source
        self.destination = destination
        self.value = value
        self.valueExtraCurrencies = valueExtraCurrencies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case opcode
        case source
        case destination
        case value
        case valueExtraCurrencies
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(opcode, forKey: .opcode)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(valueExtraCurrencies, forKey: .valueExtraCurrencies)
    }
}



